name: Build Docs
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install doxygen
        run: sudo apt install doxygen -y
      - name: Python is python3.8
        run: alias python=python3.8
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Docs Deps
        run: python -m pip install -r requirements.txt
        working-directory: ./doc
      - name: Install Bug Workaround Deps
        run: python -m pip install markupsafe==2.0.1
        working-directory: ./doc
      - name: Build Docs
        run: make html
        working-directory: ./doc
        continue-on-error: true
      - run: ls './doc/.build/html'
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.5
        with:
          publish-dir: './doc/.build/html'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: false
          alias: stt
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
